# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/solomspd.AUC/project_1/project_1.cache/wt [current_project]
set_property parent.project_path C:/Users/solomspd.AUC/project_1/project_1.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:basys3:part0:1.1 [current_project]
set_property ip_output_repo c:/Users/solomspd.AUC/project_1/project_1.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  C:/Users/solomspd.AUC/project_1/project_1.srcs/sources_1/new/clock_divider.v
  C:/Users/solomspd.AUC/project_1/project_1.srcs/sources_1/new/debouncer.v
  C:/Users/solomspd.AUC/project_1/project_1.srcs/sources_1/new/sync.v
  C:/Users/solomspd.AUC/project_1/project_1.srcs/sources_1/new/basic_cycle.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/solomspd.AUC/project_1/project_1.srcs/constrs_1/new/const.xdc
set_property used_in_implementation false [get_files C:/Users/solomspd.AUC/project_1/project_1.srcs/constrs_1/new/const.xdc]


synth_design -top basic_cycle -part xc7a35tcpg236-1


write_checkpoint -force -noxdef basic_cycle.dcp

catch { report_utilization -file basic_cycle_utilization_synth.rpt -pb basic_cycle_utilization_synth.pb }
